/**
 * The design tokens the server-rendered artwork needs, as plain values.
 *
 * Everything the browser paints reads the tokens out of `globals.css`. These
 * three surfaces cannot: the share card and the OG card are rasterised by
 * satori, which has no cascade and no custom properties, and the icons are
 * generated by a Node script before Next has run at all.
 *
 * So this file is the one place outside `globals.css` where those hexes are
 * written down, and it is deliberately a mirror rather than a second source —
 * the order and the names match the token table in CLAUDE.md. Change the
 * prototype first, then `globals.css`, then here.
 */

export const brand = {
  bg: '#F5F1EA',
  surface: '#FBF9F5',
  surface2: '#EFEAE1',
  ink: '#1F1C18',
  ink2: '#5C554C',
  muted: '#8A8177',
  line: '#E3DCD0',
  line2: '#CFC6B8',
  accent: '#2F5D62',
  correct: '#5B8C5A',
  present: '#C9A227',
  absent: '#A9A196',
  onTile: '#F5F1EA',
} as const

/** `--r-s`, as a fraction of a tile's side. 6px on the 56px board tile. */
export const TILE_RADIUS_RATIO = 6 / 56

/**
 * The wordmark's own tile: the green `W` that opens `W O R D S` on the home
 * screen. Every icon in the product is this one shape at a different scale.
 */
export const MARK_LETTER = 'W'

/** The home hero's demo row, which the OG card reuses verbatim. */
export const HERO_TILES: readonly (readonly [string, string])[] = [
  ['W', brand.correct],
  ['O', brand.present],
  ['R', brand.absent],
  ['D', brand.correct],
  ['S', brand.present],
]

export const TAGLINE =
  'Unlimited word puzzles. Same words as your friends, whenever you want to play.'
