/**
 * Regenerate the server-side guess lists from `docs/wordlists/wordlists.json`.
 *
 *   deno task build:guesses          # from supabase/functions
 *
 * Why the words are embedded rather than stored in Postgres: `word_bank` holds
 * ANSWERS only, on purpose — it is the table nobody may read. The guess list is
 * a spelling dictionary, not a secret, and `submit-guess` needs it on the hot
 * path for every single guess. Embedding it keeps that check in-process instead
 * of adding a round trip, and keeps the deploy free of a second seed step.
 *
 * The client ships the same lists as static JSON for its offline spelling
 * check; the server list is the authority. Both derive from the same source, so
 * rerun this task whenever `docs/wordlists/wordlists.json` changes.
 */

import { MODES } from '@wordroom/shared'

const SOURCE = new URL('../../../../docs/wordlists/wordlists.json', import.meta.url)

interface WordLists {
  [len: string]: { answers?: unknown; guesses?: unknown } | undefined
}

function collect(raw: WordLists, len: number): string[] {
  const guesses = raw[String(len)]?.guesses
  if (!Array.isArray(guesses)) {
    throw new Error(`wordlists.json: no guesses array for length ${len}`)
  }

  const seen = new Set<string>()
  for (const entry of guesses) {
    const word = String(entry).trim().toLowerCase()
    if (word.length !== len || !/^[a-z]+$/.test(word)) {
      console.warn(`warn: ${len}-letter: rejected ${JSON.stringify(entry)}`)
      continue
    }
    seen.add(word)
  }

  // Answers must be guessable too, or a player could not type the solution.
  const answers = raw[String(len)]?.answers
  if (Array.isArray(answers)) {
    for (const entry of answers) {
      const word = String(entry).trim().toLowerCase()
      if (word.length === len && /^[a-z]+$/.test(word)) seen.add(word)
    }
  }

  return [...seen].sort()
}

function render(len: number, words: string[]): string {
  return [
    '// Generated by _shared/guess-list/build.ts. Do not edit by hand.',
    `// ${words.length} ${len}-letter guess words from docs/wordlists/wordlists.json.`,
    '//',
    '// This is the spelling dictionary, not the answer list. It is deliberately',
    '// not a secret: the browser ships the same words. Answers live in word_bank.',
    '',
    `export default \`${words.join('\n')}\``,
    '',
  ].join('\n')
}

if (import.meta.main) {
  const raw = JSON.parse(await Deno.readTextFile(SOURCE)) as WordLists

  for (const len of MODES) {
    const words = collect(raw, len)
    const target = new URL(`./words-${len}.ts`, import.meta.url)
    await Deno.writeTextFile(target, render(len, words))
    console.error(`wrote words-${len}.ts: ${words.length} words`)
  }
}
