// @ts-check
/**
 * Regenerate the client guess lists from `docs/wordlists/wordlists.json`.
 *
 *   node apps/web/features/game/guess-list/build.mjs
 *
 * This is the same transformation `supabase/functions/_shared/guess-list/build.ts`
 * runs for the server, deliberately: both sides must agree on what counts as a
 * word, or the browser would shake at a guess the server would have accepted.
 * Rerun both whenever the word lists change.
 *
 * SECURITY. This is the *guess* list — a spelling dictionary, not the answer
 * list. Answers live in `word_bank`, which no client may read. The answer words
 * are folded in here for the same reason the server folds them in: a player has
 * to be able to type the solution. They are indistinguishable inside the list,
 * and CLAUDE.md's rule is about `puzzles.answer`, not about which English words
 * exist.
 *
 * The words are emitted as one newline-joined template literal rather than an
 * array, because 8,636 quoted strings is 8,636 lines for Biome to format and
 * roughly twice the bytes over the wire.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const SOURCE = join(HERE, '../../../../../docs/wordlists/wordlists.json')

const MODES = [5, 6, 7]

/**
 * @param {Record<string, { answers?: unknown; guesses?: unknown } | undefined>} raw
 * @param {number} len
 * @returns {string[]}
 */
function collect(raw, len) {
  const guesses = raw[String(len)]?.guesses
  if (!Array.isArray(guesses)) {
    throw new Error(`wordlists.json: no guesses array for length ${len}`)
  }

  const seen = new Set()
  for (const entry of guesses) {
    const word = String(entry).trim().toLowerCase()
    if (word.length !== len || !/^[a-z]+$/.test(word)) continue
    seen.add(word)
  }

  // Answers must be guessable too, or a player could not type the solution.
  const answers = raw[String(len)]?.answers
  if (Array.isArray(answers)) {
    for (const entry of answers) {
      const word = String(entry).trim().toLowerCase()
      if (word.length === len && /^[a-z]+$/.test(word)) seen.add(word)
    }
  }

  return [...seen].sort()
}

/**
 * @param {number} len
 * @param {string[]} words
 */
function render(len, words) {
  return [
    '// Generated by features/game/guess-list/build.mjs. Do not edit by hand.',
    `// ${words.length} ${len}-letter guess words from docs/wordlists/wordlists.json.`,
    '//',
    '// The spelling dictionary, not the answer list — the same words the server',
    '// checks against. Answers live in word_bank, which no client may read.',
    '//',
    '// Loaded through a dynamic import so it never lands in the initial bundle.',
    '',
    `export default \`${words.join('\n')}\``,
    '',
  ].join('\n')
}

const raw = JSON.parse(readFileSync(SOURCE, 'utf8'))

for (const len of MODES) {
  const words = collect(raw, len)
  writeFileSync(join(HERE, `words-${len}.ts`), render(len, words))
  process.stderr.write(`wrote words-${len}.ts: ${words.length} words\n`)
}
